### PR TITLE
lnd v0.11.0: add REST endpoint description, enable WebSocket examples

### PR DESCRIPTION
**Pull request by guggero**
Includes a number of small fixes to some of the templates and enables the WebSocket examples for streaming REST responses to be shown by default.

### CODE REVIEW

**Comment by guggero** [comment]
@wpaulino PTAL

**Comment by guggero** [comment]
@Roasbeef can I haz merge permissions please? Or could you press the button please?

**Comment by Roasbeef** [comment]
Privs bumped!

**Comment by guggero** [comment]
Thx!

**Pull request merged**
